language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - development

script: ./gradlew check --info --continue

before_install:
  - pip install --user codecov

after_success:
  - ./gradlew codeCoverageReport
  - codecov

addons:
  coverity_scan:
    project:
      name: jayware/entity-essentials
    notification_email: developers@jayware.org
    build_command_prepend: cov-configure --java
    build_command: gradle build -x test
    branch_pattern: coverity
