++++
<p align="center">
    <img src="http://jayware.github.io/entity-essentials/assets/images/e2-logo.svg" height="250" alt="Entity Essentials">
</p>
<p>
    <h1>Entity Essentials - E<sup>2</sup></h1>
<table>
    <thead>
        <tr>
            <th align="center" colspan="3">master</th>
            <th align="center" colspan="3">development</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td align="center">
                <a href="https://travis-ci.org/jayware/entity-essentials">
                    <img src="https://travis-ci.org/jayware/entity-essentials.svg?branch=master" alt="Build Status">
                </a>
            </td>
            <td align="center">
                <a href="https://codecov.io/gh/jayware/entity-essentials">
                  <img src="https://codecov.io/gh/jayware/entity-essentials/branch/master/graph/badge.svg" alt="Codecov" />
                </a>
            </td>
            <td align="center">
                <a href="https://www.versioneye.com/user/projects/56b464390a0ff50035ba7e9f?child=summary">
                    <img src="https://www.versioneye.com/user/projects/56b464390a0ff50035ba7e9f/badge.svg?style=flat" alt="Dependency Status" />
                </a>
            </td>
            <td align="center">
                <a href="https://travis-ci.org/jayware/entity-essentials">
                    <img src="https://travis-ci.org/jayware/entity-essentials.svg?branch=development" alt="Build Status">
                </a>
            </td>
            <td align="center">
                <a href="https://codecov.io/gh/jayware/entity-essentials">
                  <img src="https://codecov.io/gh/jayware/entity-essentials/branch/development/graph/badge.svg" alt="Codecov" />
                </a>
            </td>
            <td align="center">
                <a href="https://www.versioneye.com/user/projects/56b465e30a0ff5002c85efe0?child=summary">
                    <img src="https://www.versioneye.com/user/projects/56b465e30a0ff5002c85efe0/badge.svg?style=flat" alt="Dependency Status" />
                </a>
            </td>
        </tr>
    </tbody>
</table>
</p>
++++

:api-version: 0.5.3
:impl-version: 0.5.3

## Description
Entity Essentials is a Component-based Entity System written in Java. This framework provides operations and structures to work with entities and components.
Apart from that, it provides a couple of useful extras. The current implementation isn't a typical https://en.wikipedia.org/wiki/Entity_component_system[Entity Component System (ECS)]
known from game development as a part of a game engine. Instead, this framework is designed as foundation when you need the most flexible runtime-model for your application.

## Quickstart
[source,java]
----
public class Quickstart
{
    public static void main(String[] args) {

        /* Create a context and obtain required managers */
        Context context = ContextProvider.getInstance().createContext();
        EntityManager entityManager = context.getService(EntityManager.class);
        ComponentManager componentManager = context.getService(ComponentManager.class);

        /* Create an entity */
        EntityRef ref = entityManager.createEntity(context);

        /* Add a component to the entity */
        componentManager.addComponent(ref, ExampleComponent.class);

        /* Lookup a component */
        ExampleComponent cmp = componentManager.getComponent(ref, ExampleComponent.class);

        /* Change the component's properties */
        cmp.setText("Fubar!");
        cmp.setTextSize(14);

        /* Commit changes */
        cmp.pushTo(ref);

        /* Shutdown everything */
        context.dispose();
    }

    /* Define a custom component by a java interface */
    public interface ExampleComponent extends Component
    {
        /* Define properties by declaration of getters and setters  */
        String getText();

        void setText(String text);

        int getTextSize();

        void setTextSize(int size);
    }
}
----

More examples can be found link:examples/README.md[here].

## Usage

### Maven coordinates

|===
| Group ID |Artifact ID | Version

| org.jayware
| entity-essentials-api
| {api-version}

| org.jayware
| entity-essentials-impl
| {impl-version}

|===

### Gradle
###### Repository
[source,groovy]
----
repositories {
   jcenter()
}
----

###### Dependencies
[source,java,subs="attributes"]
----
dependencies {
    compile group: 'org.jayware', name: 'entity-essentials-api', version: '{api-version}'
    runtime group: 'org.jayware', name: 'entity-essentials-impl', version: '{impl-version}'
}
----

### Maven
###### Repository
[source,xml]
----
<repository>
    <id>central</id>
    <name>bintray</name>
    <url>http://jcenter.bintray.com</url>
</repository>
----
###### Dependencies
[source,xml]
----
<dependency>
    <groupId>org.jayware</groupId>
    <artifactId>entity-essentials-api</artifactId>
    <version>0.5.3</version>
</dependency>
<dependency>
    <groupId>org.jayware</groupId>
    <artifactId>entity-essentials-impl</artifactId>
    <version>0.5.3</version>
    <scope>runtime</scope>
</dependency>
----

### Direct Download

|===
|https://jcenter.bintray.com/org/jayware/entity-essentials-api/{api-version}/[entity-essentials-api] |https://jcenter.bintray.com/org/jayware/entity-essentials-impl/{impl-version}/[entity-essentials-impl]
|===

## Contributions
All contributions are welcome: ideas, patches, documentation, bug reports, complaints.